In [2]:
# !pip install numpy 
import numpy as np

In [4]:
mat = np.array([ [1,2,3],[2,3,4],[3,4,5] ])
mat

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [7]:
# np.arange(start=0 , stop-1 , step=1)
arr1 = np.arange(3)
arr1

array([0, 1, 2])

In [8]:
len(arr1)

3

In [9]:
arr1.size

3

In [10]:
mat.size

9

In [11]:
mat.shape

(3, 3)

In [12]:
print("Number of rows is:" , mat.shape[0])

Number of rows is: 3


In [13]:
print("Number of cols is:" , mat.shape[1])

Number of cols is: 3


In [14]:
arr1 + mat

array([[1, 3, 5],
       [2, 4, 6],
       [3, 5, 7]])

In [15]:
arr1

array([0, 1, 2])

In [19]:
arr2 = arr1.reshape((-1 , 1))
arr2

array([[0],
       [1],
       [2]])

In [20]:
arr2 + mat

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7]])

In [23]:
mat2 =np.array([[1 , 2 , 3] ,[2 , 3 , 4] ])
mat2

array([[1, 2, 3],
       [2, 3, 4]])

In [24]:
mat2.dot(mat)

array([[14, 20, 26],
       [20, 29, 38]])

In [25]:
x = np.array([1,2,3,4,5,6,7,8,9])
y = np.array([9,8,7,6,5,4,3,2,1])

In [26]:
np.mean(x)

5.0

In [27]:
np.median(y)

5.0

In [30]:
mat2

array([[1, 2, 3],
       [2, 3, 4]])

In [31]:
np.mean(mat2)

2.5

In [33]:
np.mean(mat2 , axis = 0)   # axis = 0 >> colsssssssssssss

array([1.5, 2.5, 3.5])

In [34]:
np.mean(mat2 , axis = 1)   # axis = 1 >> rowsssssssssssss

array([2., 3.])

In [35]:
np.var(x)

6.666666666666667

In [36]:
np.std(x)

2.581988897471611

In [38]:
round(np.std(x) , 1)

2.6

In [39]:
np.ceil(np.std(x))

3.0

In [40]:
np.floor(np.std(x))

2.0

In [42]:
np.cov(x,y)[ 0 , 1 ]

-7.5

In [44]:
np.corrcoef(x,y)[1 , 0]

-1.0